project:
  type: website
  render:
  - "*.qmd"
  - "*.md"

knitr:
  opts_chunk:
    root.dir: '.'

website:
  title: "ETC5513: Collaborative and Reproducible Practices"
  site-url: "https://rcp.numbat.space"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Schedule
        icon: calendar2-fill
        menu:
          - file: week1/index.qmd
            text: "Week 1: Introduction to collaborative and reproducible practices"
          - file: week2/index.qmd
            text: "Week 2: Reproducible reports using Quarto"
          - file: week3/index.qmd
            text: "Week 3: Introduction to version control systems: git and GitHub"
          - file: week4/index.qmd
            text: "Week 4: Reproducible reporting using Quarto, git and GitHub"
          - file: week5/index.qmd
            text: "Week 5: Deeper git knowledge, stashing and tools"
          - week6/index.qmd
          - week7/index.qmd
          - text: "Week 8: No class (University Holiday)"
          - week9/index.qmd
          - week10/index.qmd
          - week11/index.qmd
          - week12/index.qmd
      - text: Discussion
        icon: chat-fill
        href: "https://learning.monash.edu/mod/forum/view.php?id=2034181"
      - text: Moodle
        icon: mortarboard-fill
        href: "https://learning.monash.edu/course/view.php?id=12724&section=1"
    right:
      - icon: github
        href: https://github.com/numbats/arp

date-format: "D MMMM YYYY"

format:
  html:
    theme: [cosmo, numbat.scss]
    highlight: textmate
    toc: true
    mainfont: "Fira Sans"
    html-math-method: katex
    include-in-header:
      file: header.html


execute:
  echo: false
  warning: false
  message: false